apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-recommendation-deployment
  namespace: movies-recommendation
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: movies-recommendation
  template:
    metadata:
      labels:
        app: movies-recommendation
    spec:
      containers:
      - name: movies-recommendation
        image: docker.io/pgrzadko/movies-recommendation:1.2
        ports:
        - containerPort: 9000
        livenessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "pgrep php-fpm"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "pgrep php-fpm"
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
        volumeMounts:
            - name: env-config
              mountPath: /var/www/html/.env
              subPath: .env
        resources:
          requests:
            cpu: 400m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1.5Gi
            
      volumes:
        - name: env-config
          configMap:
            name: php-env-config