apiVersion: v1
kind: Service
metadata:
  name: movies-recommendation-svc
  namespace: movies-recommendation
spec:
  selector:
    app: movies-recommendation
  type: ClusterIP
  ports:
   -  protocol: TCP
      port: 9000
      targetPort: 9000